import { chromium } from 'playwright-core'
import { existsSync } from 'node:fs'
const EDGE = ['C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', 'C:/Program Files/Google/Chrome/Application/chrome.exe'].filter((p) => existsSync(p))
const browser = await chromium.launch({ executablePath: EDGE[0], headless: true })
const page = await browser.newPage()
await page.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await page.getByRole('button', { name: '新建对象' }).first().waitFor({ timeout: 10000 })
await page.getByRole('button', { name: '新建对象' }).first().click()
await page.getByLabel('标题').fill('加列对象')
await page.getByRole('button', { name: '创建' }).click()
await page.getByRole('button', { name: /新笔记/ }).first().click()
await page.getByLabel('标题').fill('加列笔记')
await page.getByRole('button', { name: '保存' }).click()
await page.getByText('加列笔记').first().click()
await page.locator('.cm-content').waitFor()
await page.waitForTimeout(300)
await page.getByRole('button', { name: '表格', exact: true }).click()
await page.waitForTimeout(300)
await page.getByRole('button', { name: '＋列', exact: true }).click()
await page.waitForTimeout(400)
const r = await page.evaluate(async () => {
  const { EditorView } = await import('/node_modules/.vite/deps/@codemirror_view.js')
  const view = EditorView.findFromDOM(document.querySelector('.cm-content'))
  return { doc: view.state.doc.toString(), toolbar: document.querySelectorAll('.sn-table-toolbar').length }
})
console.log('doc:', JSON.stringify(r.doc))
console.log('toolbar:', r.toolbar)
await browser.close()
